# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 417620bca161f72fd9c2db53631cb42cce4868669da82666b0d4084f17760bb785f35368bfb2620233549021b04284813497c9817c40e270932e752e8473ee79

test:
  secret_key_base: a30a94df30f79861485f661c10634d7cf7579c9a66589d53258bdc51cd27469cf8e360ec8c237cbd9176827de6edda832e9ebdcc7c5d0766202a3d60415fdc6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
